### ISSUE TITLE
打扰一下。用这个项目闪讯拨号和拦截，都不成功。

### ISSUE THREAD

**Issue by jhuqin** [cc5771027/feed-netkeeper#15]
大神，你好，用您这个项目，闪讯和拦截那个方式都不能成功，后来用其他人项目的拦截方式，可以用https://github.com/goodwinY/netkeeper项目是这个，麻烦您看看，能不能参考这个项目出一个ipk的安装方式和带luci界面的。那种方式安装麻烦。谢谢大神了。如有打扰到话，请谅解。

**Comment by jhuqin** [comment]
https://github.com/goodwinY/netkeeper

**Comment by v8wzge** [comment]
这个项目其实是可以使用拦截的，不过和使用脚本的拦截法相比联网慢一点，拨号应该是都不能用，这是miao007大佬验证的

**Comment by jhuqin** [comment]
哦 ，好的，谢谢大神解答。对了可否按上面他到那个拦截项目，编译一个单独拦截的ipk项目，可以通过ipk的方式安装。谢谢大神。

**Comment by v8wzge** [comment]
不行，一开始我也是这样做，但是只能拦截不能拨号，后来编译进固件就解决了

**Comment by v8wzge** [comment]
推荐用官方源码编译，lede编译出来的虽然也可以用，但是小bug不断，扰人心态

**Comment by jhuqin** [comment]
您好，我就是用lede编译的您的项目，拦截那个不管用，所以来咨询您的，官方的我等会去试下。还有别人的那个拦截项目是，把获取到的账号和密码，自动填到wan口pppoe对应账号和密码，账号前面会带字符，然后自动拨号，所以成功的，您的这个项目原理也是一样的么。

**Comment by v8wzge** [comment]
我不是开发者，你有没有发现他们都有提到miao1007，他才是整个项目的基石，

**Comment by v8wzge** [comment]
https://github.com/miao1007/Openwrt-NetKeeper/tree/master/netkeeper4-use-pppoer-server
