### ISSUE TITLE
小白不知道怎么自行编译啊

### ISSUE THREAD

**Issue by HumbleHumbert** [cc5771027/feed-netkeeper#17]
大神！怎么自行编译啊？不懂编程。求助啊！

**Comment by Steady66666** [comment]
编译不需要会编程，写了个Windows子系统的教程，小白教程，我也是小白
需要feed-netkeeper的话进入目录 “cd lede/packages && git clone https://github.com/CCnut/feed-netkeeper.git"
冒号为命令，目录不是完整目录，该命令是在你默认用户路径下输入才有效（开机即默认目录）
https://www.angqin.xyz/archives/ang/299/
“make menuconfig”配置自己去网上找你对应设备的教程
PS:这个项目我没成功实现过，挺遗憾的，还是用的miao1007OP脚本来实现拨号

**Comment by HumbleHumbert** [comment]
> 编译不需要会编程，写了个Windows子系统的教程，小白教程，我也是小白
> 需要feed-netkeeper的话进入目录 “cd lede/packages && git clone https://github.com/CCnut/feed-netkeeper.git"
> 冒号为命令，目录不是完整目录，该命令是在你默认用户路径下输入才有效（开机即默认目录）
> https://www.angqin.xyz/archives/ang/299/
> “make menuconfig”配置自己去网上找你对应设备的教程
> PS:这个项目我没成功实现过，挺遗憾的，还是用的miao1007OP脚本来实现拨号

 感谢回复，业已用其他项目完成。
